In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/home/student/Pulpit/nypd.csv", low_memory=False)

In [38]:
df2 = df.loc[(df["CONTRIBUTING FACTOR VEHICLE 1"] == "Unsafe Speed")]
df2

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
7,2019-08-11T00:00:00.000,22:23,NaN,NaN,40.858210,-73.916790,"{'type': 'Point', 'coordinates': [-73.91679, 4...",MAJOR DEEGAN EXPRESSWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4187134,Motorcycle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
111,2019-08-09T00:00:00.000,6:00,STATEN ISLAND,10312,40.531110,-74.157234,"{'type': 'Point', 'coordinates': [-74.157234, ...",NaN,NaN,4514 HYLAN BOULEVARD,...,Unspecified,NaN,NaN,NaN,4187379,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
190,2019-08-17T00:00:00.000,2:45,NaN,NaN,40.814266,-73.912964,"{'type': 'Point', 'coordinates': [-73.912964, ...",EAST 149 STREET,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4191503,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
219,2019-08-30T00:00:00.000,17:15,NaN,NaN,40.866062,-73.922510,"{'type': 'Point', 'coordinates': [-73.92251, 4...",VERMILYEA AVENUE,NaN,NaN,...,Driver Inattention/Distraction,Unspecified,Unspecified,NaN,4200221,Motorcycle,Sedan,Station Wagon/Sport Utility Vehicle,Box Truck,NaN
270,2019-08-03T00:00:00.000,21:00,NaN,NaN,40.848118,-73.930890,"{'type': 'Point', 'coordinates': [-73.93089, 4...",WEST 181 STREET,NaN,NaN,...,Unspecified,Unspecified,NaN,NaN,4182747,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1608816,2012-08-10T00:00:00.000,5:45,BRONX,10461,40.838309,-73.828930,"{'type': 'Point', 'coordinates': [-73.82893, 4...",CROSBY AVENUE,WATERBURY AVENUE,NaN,...,Unspecified,Unspecified,NaN,NaN,88793,OTHER,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
1610213,2012-07-17T00:00:00.000,7:15,BRONX,10455,40.813095,-73.898259,"{'type': 'Point', 'coordinates': [-73.8982589,...",BRUCKNER BOULEVARD,LEGGETT AVENUE,NaN,...,NaN,NaN,NaN,NaN,76272,PASSENGER VEHICLE,NaN,NaN,NaN,NaN
1610399,2012-07-12T00:00:00.000,12:40,NaN,NaN,NaN,NaN,NaN,BRUCKNER BOULEVARD,EAST 135 STREET,NaN,...,Unspecified,Unspecified,NaN,NaN,72670,VAN,SPORT UTILITY / STATION WAGON,SMALL COM VEH(4 TIRES),NaN,NaN
1610625,2012-07-01T00:00:00.000,3:50,MANHATTAN,10014,40.733373,-74.002573,"{'type': 'Point', 'coordinates': [-74.0025727,...",GROVE STREET,WEST 4 STREET,NaN,...,Unspecified,NaN,NaN,NaN,9399,VAN,PASSENGER VEHICLE,NaN,NaN,NaN
1610834,2012-07-20T00:00:00.000,21:15,MANHATTAN,10018,40.757672,-73.994824,"{'type': 'Point', 'coordinates': [-73.9948239,...",WEST 40 STREET,DYER AVENUE,NaN,...,Unspecified,NaN,NaN,NaN,16696,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN

In [39]:
df3 = df.loc[(df["CONTRIBUTING FACTOR VEHICLE 2"] == "Unsafe Speed")]
df3

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
14,2019-08-12T00:00:00.000,11:20,QUEENS,11420,40.678550,-73.814220,"{'type': 'Point', 'coordinates': [-73.81422, 4...",NaN,NaN,125-05 115 AVENUE,...,Unsafe Speed,NaN,NaN,NaN,4187599,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
1072,2019-08-24T00:00:00.000,21:00,QUEENS,11413,40.676155,-73.755660,"{'type': 'Point', 'coordinates': [-73.75566, 4...",SPRINGFIELD BOULEVARD,CARSON STREET,NaN,...,Unsafe Speed,NaN,NaN,NaN,4194056,Sedan,Sedan,NaN,NaN,NaN
1866,2019-08-15T00:00:00.000,15:18,MANHATTAN,10029,40.797943,-73.942130,"{'type': 'Point', 'coordinates': [-73.94213, 4...",LEXINGTON AVENUE,EAST 115 STREET,NaN,...,Unsafe Speed,NaN,NaN,NaN,4189351,Sedan,Sedan,NaN,NaN,NaN
1966,2019-08-07T00:00:00.000,15:59,BROOKLYN,11204,40.621670,-73.991264,"{'type': 'Point', 'coordinates': [-73.991264, ...",63 STREET,17 AVENUE,NaN,...,Unsafe Speed,NaN,NaN,NaN,4184771,Sedan,Sedan,NaN,NaN,NaN
2029,2019-08-18T00:00:00.000,9:20,NaN,NaN,NaN,NaN,NaN,MASON AVENUE,NaN,NaN,...,Unsafe Speed,NaN,NaN,NaN,4190302,Sedan,Sedan,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1561363,2012-10-02T00:00:00.000,18:30,NaN,NaN,40.804230,-73.912998,"{'type': 'Point', 'coordinates': [-73.9129984,...",NaN,NaN,NaN,...,Unsafe Speed,NaN,NaN,NaN,2879126,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
1571104,2012-10-02T00:00:00.000,18:30,NaN,NaN,40.804230,-73.912998,"{'type': 'Point', 'coordinates': [-73.9129984,...",NaN,NaN,NaN,...,Unsafe Speed,NaN,NaN,NaN,2879126,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN,NaN
1586821,2012-08-11T00:00:00.000,19:40,BROOKLYN,11222,40.732323,-73.954609,"{'type': 'Point', 'coordinates': [-73.9546088,...",INDIA STREET,MANHATTAN AVENUE,NaN,...,Unsafe Speed,NaN,NaN,NaN,198375,PASSENGER VEHICLE,BICYCLE,NaN,NaN,NaN
1599030,2012-08-11T00:00:00.000,19:40,BROOKLYN,11222,40.732323,-73.954609,"{'type': 'Point', 'coordinates': [-73.9546088,...",INDIA STREET,MANHATTAN AVENUE,NaN,...,Unsafe Speed,NaN,NaN,NaN,198375,PASSENGER VEHICLE,BICYCLE,NaN,NaN,NaN
1607885,2012-07-29T00:00:00.000,22:00,QUEENS,11413,40.677393,-73.739792,"{'type': 'Point', 'coordinates': [-73.7397922,...",230 STREET,133 AVENUE,NaN,...,Unsafe Speed,NaN,NaN,NaN,219776,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN,NaN

In [40]:
df4 = df.loc[(df["CONTRIBUTING FACTOR VEHICLE 3"] == "Unsafe Speed")]
df4

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
10186,2019-08-28T00:00:00.000,3:15,NaN,NaN,40.673107,-73.999590,"{'type': 'Point', 'coordinates': [-73.99959, 4...",BROOKLYN QUEENS EXPRESSWAY,NaN,NaN,...,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN,NaN,4196297,Sedan,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN
10264,2019-08-10T00:00:00.000,12:20,BRONX,10457,40.846810,-73.908300,"{'type': 'Point', 'coordinates': [-73.9083, 40...",EASTBURN AVENUE,EAST 175 STREET,NaN,...,Other Vehicular,Unsafe Speed,NaN,NaN,4186564,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN
12636,2019-08-03T00:00:00.000,7:57,NaN,NaN,40.740840,-73.726810,"{'type': 'Point', 'coordinates': [-73.72681, 4...",CROSS ISLAND PARKWAY,NaN,NaN,...,Driver Inattention/Distraction,Unsafe Speed,NaN,NaN,4182299,Sedan,Sedan,Pick-up Truck,NaN,NaN
13322,2019-08-13T00:00:00.000,6:10,NaN,NaN,NaN,NaN,NaN,VERRAZANO BRIDGE UPPER,NaN,NaN,...,Other Vehicular,Unsafe Speed,NaN,NaN,4188498,Sedan,Sedan,Sedan,NaN,NaN
13878,2019-08-23T00:00:00.000,22:50,NaN,NaN,40.753320,-73.963600,"{'type': 'Point', 'coordinates': [-73.9636, 40...",FDR DRIVE,NaN,NaN,...,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN,NaN,4196808,Sedan,Sedan,Station Wagon/Sport Utility Vehicle,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870929,2016-06-26T00:00:00.000,1:00,NaN,NaN,NaN,NaN,NaN,BELT PARKWAY,NaN,NaN,...,Unsafe Speed,Unsafe Speed,Unspecified,Unspecified,3470008,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE
907609,2015-11-24T00:00:00.000,14:15,NaN,NaN,40.596545,-74.002465,"{'type': 'Point', 'coordinates': [-74.0024648,...",NaN,NaN,NaN,...,Unsafe Speed,Unsafe Speed,NaN,NaN,3340673,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN,NaN
924626,2016-02-20T00:00:00.000,21:00,BROOKLYN,11221,40.694001,-73.923500,"{'type': 'Point', 'coordinates': [-73.9234996,...",GREENE AVENUE,EVERGREEN AVENUE,NaN,...,Unsafe Speed,Unsafe Speed,NaN,NaN,3392973,OTHER,OTHER,OTHER,NaN,NaN
932289,2016-02-05T00:00:00.000,14:57,NaN,NaN,40.790754,-73.981365,"{'type': 'Point', 'coordinates': [-73.9813646,...",NaN,NaN,NaN,...,Fatigued/Drowsy,Unsafe Speed,NaN,NaN,3383960,PASSENGER VEHICLE,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,NaN,NaN
1157420,2015-03-26T00:00:00.000,15:03,NaN,NaN,40.643849,-73.875753,"{'type': 'Point', 'coordinates': [-73.8757525,...",NaN,NaN,NaN,...,Fatigued/Drowsy,Unsafe Speed,Unspecified,NaN,3193132,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN

In [41]:
df5 = df.loc[(df["CONTRIBUTING FACTOR VEHICLE 4"] == "Unsafe Speed")]
df5

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
8400,2019-08-07T00:00:00.000,11:20,NaN,NaN,40.697980,-73.726970,"{'type': 'Point', 'coordinates': [-73.72697, 4...",CROSS ISLAND PARKWAY,NaN,NaN,...,Following Too Closely,Following Too Closely,Unsafe Speed,Unspecified,4184547,Sedan,Taxi,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
149396,2019-08-07T00:00:00.000,11:20,NaN,NaN,40.697980,-73.726970,"{'type': 'Point', 'coordinates': [-73.72697, 4...",CROSS ISLAND PARKWAY,NaN,NaN,...,Following Too Closely,Following Too Closely,Unsafe Speed,Unspecified,4184547,Sedan,Taxi,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
220579,2018-09-01T00:00:00.000,23:45,NaN,NaN,40.820343,-73.959335,"{'type': 'Point', 'coordinates': [-73.959335, ...",HENRY HUDSON PARKWAY,NaN,NaN,...,Driver Inattention/Distraction,Driver Inattention/Distraction,Unsafe Speed,Driver Inattention/Distraction,3972007,Sedan,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle
275006,2018-09-01T00:00:00.000,23:45,NaN,NaN,40.820343,-73.959335,"{'type': 'Point', 'coordinates': [-73.959335, ...",HENRY HUDSON PARKWAY,NaN,NaN,...,Driver Inattention/Distraction,Driver Inattention/Distraction,Unsafe Speed,Driver Inattention/Distraction,3972007,Sedan,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle
374387,2018-04-06T00:00:00.000,6:00,BROOKLYN,11212,40.673985,-73.906970,"{'type': 'Point', 'coordinates': [-73.90697, 4...",EAST NEW YORK AVENUE,CHRISTOPHER AVENUE,NaN,...,Following Too Closely,Following Too Closely,Unsafe Speed,NaN,3876333,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,CM,NaN
378436,2018-03-22T00:00:00.000,9:00,BRONX,10461,40.852238,-73.850630,"{'type': 'Point', 'coordinates': [-73.85063, 4...",NaN,NaN,1855 HERING AVENUE,...,Other Vehicular,Other Vehicular,Unsafe Speed,NaN,3868464,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN
385814,2018-05-27T00:00:00.000,10:03,BRONX,10468,40.861660,-73.910965,"{'type': 'Point', 'coordinates': [-73.910965, ...",NaN,NaN,264 WEST FORDHAM ROAD,...,Other Vehicular,Other Vehicular,Unsafe Speed,NaN,3908528,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle,Sedan,NaN
420165,2018-04-06T00:00:00.000,6:00,BROOKLYN,11212,40.673985,-73.906970,"{'type': 'Point', 'coordinates': [-73.90697, 4...",EAST NEW YORK AVENUE,CHRISTOPHER AVENUE,NaN,...,Following Too Closely,Following Too Closely,Unsafe Speed,NaN,3876333,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,CM,NaN
424212,2018-03-22T00:00:00.000,9:00,BRONX,10461,40.852238,-73.850630,"{'type': 'Point', 'coordinates': [-73.85063, 4...",NaN,NaN,1855 HERING AVENUE,...,Other Vehicular,Other Vehicular,Unsafe Speed,NaN,3868464,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN
443365,2018-03-09T00:00:00.000,13:30,NaN,NaN,40.877870,-73.870100,"{'type': 'Point', 'coordinates': [-73.8701, 40...",BRONX RIVER PARKWAY,NaN,NaN,...,Driver Inattention/Distraction,Driver Inattention/Distraction,Unsafe Speed,Unspecified,3860055,PICK-UP TRUCK,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE
473456,2016-11-09T00:00:00.000,21:50,NaN,NaN,40.699930,-73.961880,"{'type': 'Point', 'coordinates': [-73.96188, 4...",BROOKLYN QUEENS EXPRESSWAY,NaN,NaN,...,Other Vehicular,Other Vehicular,Unsafe Speed,NaN,3558072,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN
505215,2018-02-06T00:00:00.000,0:20,QUEENS,11419,40.686600,-73.829830,"{'type': 'Point', 'coordinates': [-73.82983, 4...",NaN,NaN,113-11 103 AVENUE,...,Other Vehicular,Other Vehicular,Unsafe Speed,NaN,3842905,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN
506930,2018-01-27T00:00:00.000,14:10,NaN,NaN,40.767612,-73.950005,"{'type': 'Point', 'coordinates': [-73.950005, ...",FDR DRIVE,NaN,NaN,...,Driver Inattention/Distraction,Driver Inattention/Distraction,Unsafe Speed,NaN,3836654,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,SPORT UTILITY / STATION WAGON,NaN,NaN
630306,2017-02-12T00:00:00.000,3:30,NaN,NaN,40.735283,-73.859840,"{'type': 'Point', 'coordinates': [-73.85984, 4...",LONG ISLAND EXPRESSWAY,NaN,NaN,...,Unsafe Speed,Unsafe Speed,Unsafe Speed,Unsafe Speed,3613818,TAXI,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE
692502,2016-11-09T00:00:00.000,0:10,NaN,NaN,40.674250,-73.801450,"{'type': 'Point', 'coordinates': [-73.80145, 4...",VANWYCK EXPRESSWAY,ROCKAWAY BOULEVARD,NaN,...,Other Vehicular,Other Vehicular,Unsafe Speed,NaN,3559830,PASSENGER VEHICLE,PASSENGER VEHICLE,SPORT UTILITY / STATION WAGON,PASSENGER VEHICLE,PASSENGER VEHICLE
705078,2016-10-11T00:00:00.000,8:10,NaN,NaN,NaN,NaN,NaN,NORMAN AVENUE,NaN,NaN,...,Unsafe Speed,Failure to Yield Right-of-Way,Unsafe Speed,Failure to Yield Right-of-Way,3542243,PASSENGER VEHICLE,BICYCLE,PASSENGER VEHICLE,BICYCLE,PASSENGER VEHICLE
751045,2016-07-23T00:00:00.000,12:23,BRONX,10457,40.849213,-73.905760,"{'type': 'Point', 'coordinates': [-73.90576, 4...",MONROE AVENUE,EAST TREMONT AVENUE,NaN,...,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN,3486782,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN
761012,2016-10-11T00:00:00.000,8:10,NaN,NaN,NaN,NaN,NaN,NORMAN AVENUE,NaN,NaN,...,Unsafe Speed,Failure to Yield Right-of-Way,Unsafe Speed,Failure to Yield Right-of-Way,3542243,PASSENGER VEHICLE,BICYCLE,PASSENGER VEHICLE,BICYCLE,PASSENGER VEHICLE
819763,2016-03-26T00:00:00.000,3:02,NaN,NaN,NaN,NaN,NaN,EAST 138 STREET,PARK AVENUE,NaN,...,Other Vehicular,Other Vehicular,Unsafe Speed,Other Vehicular,3410988,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE
850246,2016-07-23T00:00:00.000,12:23,BRONX,10457,40.849213,-73.905760,"{'type': 'Point', 'coordinates': [-73.90576, 4...",MONROE AVENUE,EAST TREMONT AVENUE,NaN,...,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN,3486782,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN

In [43]:
df6 = df.loc[(df["CONTRIBUTING FACTOR VEHICLE 5"] == "Unsafe Speed")]
df6

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
555,2019-08-20T00:00:00.000,22:00,NaN,NaN,40.717014,-73.799400,"{'type': 'Point', 'coordinates': [-73.7994, 40...",GRAND CENTRAL PKWY,NaN,NaN,...,Following Too Closely,Following Too Closely,Following Too Closely,Unsafe Speed,4192543,Sedan,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
62926,2019-10-19T00:00:00.000,8:45,NaN,NaN,40.609505,-74.181885,"{'type': 'Point', 'coordinates': [-74.181885, ...",WEST SHORE EXPRESSWAY,NaN,NaN,...,Driver Inexperience,Driver Inattention/Distraction,Following Too Closely,Unsafe Speed,4228781,Sedan,Sedan,Station Wagon/Sport Utility Vehicle,Sedan,Sedan
141639,2019-08-20T00:00:00.000,22:00,NaN,NaN,40.717014,-73.799400,"{'type': 'Point', 'coordinates': [-73.7994, 40...",GRAND CENTRAL PKWY,NaN,NaN,...,Following Too Closely,Following Too Closely,Following Too Closely,Unsafe Speed,4192543,Sedan,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
630306,2017-02-12T00:00:00.000,3:30,NaN,NaN,40.735283,-73.859840,"{'type': 'Point', 'coordinates': [-73.85984, 4...",LONG ISLAND EXPRESSWAY,NaN,NaN,...,Unsafe Speed,Unsafe Speed,Unsafe Speed,Unsafe Speed,3613818,TAXI,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE

In [46]:
data_raw = pd.concat([df2,df3,df4,df5,df6], ignore_index=True)
data_raw

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,ZIP CODE,LATITUDE,LONGITUDE,LOCATION,ON STREET NAME,CROSS STREET NAME,OFF STREET NAME,...,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,COLLISION_ID,VEHICLE TYPE CODE 1,VEHICLE TYPE CODE 2,VEHICLE TYPE CODE 3,VEHICLE TYPE CODE 4,VEHICLE TYPE CODE 5
0,2019-08-11T00:00:00.000,22:23,NaN,NaN,40.858210,-73.916790,"{'type': 'Point', 'coordinates': [-73.91679, 4...",MAJOR DEEGAN EXPRESSWAY,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4187134,Motorcycle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
1,2019-08-09T00:00:00.000,6:00,STATEN ISLAND,10312,40.531110,-74.157234,"{'type': 'Point', 'coordinates': [-74.157234, ...",NaN,NaN,4514 HYLAN BOULEVARD,...,Unspecified,NaN,NaN,NaN,4187379,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN,NaN
2,2019-08-17T00:00:00.000,2:45,NaN,NaN,40.814266,-73.912964,"{'type': 'Point', 'coordinates': [-73.912964, ...",EAST 149 STREET,NaN,NaN,...,Unspecified,NaN,NaN,NaN,4191503,Station Wagon/Sport Utility Vehicle,Sedan,NaN,NaN,NaN
3,2019-08-30T00:00:00.000,17:15,NaN,NaN,40.866062,-73.922510,"{'type': 'Point', 'coordinates': [-73.92251, 4...",VERMILYEA AVENUE,NaN,NaN,...,Driver Inattention/Distraction,Unspecified,Unspecified,NaN,4200221,Motorcycle,Sedan,Station Wagon/Sport Utility Vehicle,Box Truck,NaN
4,2019-08-03T00:00:00.000,21:00,NaN,NaN,40.848118,-73.930890,"{'type': 'Point', 'coordinates': [-73.93089, 4...",WEST 181 STREET,NaN,NaN,...,Unspecified,Unspecified,NaN,NaN,4182747,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16313,2016-07-23T00:00:00.000,12:23,BRONX,10457,40.849213,-73.905760,"{'type': 'Point', 'coordinates': [-73.90576, 4...",MONROE AVENUE,EAST TREMONT AVENUE,NaN,...,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN,3486782,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,NaN
16314,2019-08-20T00:00:00.000,22:00,NaN,NaN,40.717014,-73.799400,"{'type': 'Point', 'coordinates': [-73.7994, 40...",GRAND CENTRAL PKWY,NaN,NaN,...,Following Too Closely,Following Too Closely,Following Too Closely,Unsafe Speed,4192543,Sedan,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
16315,2019-10-19T00:00:00.000,8:45,NaN,NaN,40.609505,-74.181885,"{'type': 'Point', 'coordinates': [-74.181885, ...",WEST SHORE EXPRESSWAY,NaN,NaN,...,Driver Inexperience,Driver Inattention/Distraction,Following Too Closely,Unsafe Speed,4228781,Sedan,Sedan,Station Wagon/Sport Utility Vehicle,Sedan,Sedan
16316,2019-08-20T00:00:00.000,22:00,NaN,NaN,40.717014,-73.799400,"{'type': 'Point', 'coordinates': [-73.7994, 40...",GRAND CENTRAL PKWY,NaN,NaN,...,Following Too Closely,Following Too Closely,Following Too Closely,Unsafe Speed,4192543,Sedan,Station Wagon/Sport Utility Vehicle,Sedan,Station Wagon/Sport Utility Vehicle,Station Wagon/Sport Utility Vehicle
16317,2017-02-12T00:00:00.000,3:30,NaN,NaN,40.735283,-73.859840,"{'type': 'Point', 'coordinates': [-73.85984, 4...",LONG ISLAND EXPRESSWAY,NaN,NaN,...,Unsafe Speed,Unsafe Speed,Unsafe Speed,Unsafe Speed,3613818,TAXI,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE,PASSENGER VEHICLE

In [64]:
columns_list = ["ZIP CODE","LATITUDE","LONGITUDE","LOCATION","ON STREET NAME","CROSS STREET NAME","OFF STREET NAME","COLLISION_ID","VEHICLE TYPE CODE 1", "VEHICLE TYPE CODE 2","VEHICLE TYPE CODE 3","VEHICLE TYPE CODE 4","VEHICLE TYPE CODE 5"]
data = data_raw.drop(columns_list,axis=1)
data

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5
0,2019-08-11T00:00:00.000,22:23,NaN,0.0,1.0,0,0,0,0,0,1,Unsafe Speed,Unspecified,NaN,NaN,NaN
1,2019-08-09T00:00:00.000,6:00,STATEN ISLAND,2.0,0.0,0,0,0,0,2,0,Unsafe Speed,Unspecified,NaN,NaN,NaN
2,2019-08-17T00:00:00.000,2:45,NaN,2.0,0.0,0,0,0,0,2,0,Unsafe Speed,Unspecified,NaN,NaN,NaN
3,2019-08-30T00:00:00.000,17:15,NaN,1.0,0.0,0,0,0,0,1,0,Unsafe Speed,Driver Inattention/Distraction,Unspecified,Unspecified,NaN
4,2019-08-03T00:00:00.000,21:00,NaN,3.0,0.0,0,0,0,0,3,0,Unsafe Speed,Unspecified,Unspecified,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16313,2016-07-23T00:00:00.000,12:23,BRONX,0.0,0.0,0,0,0,0,0,0,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN
16314,2019-08-20T00:00:00.000,22:00,NaN,1.0,0.0,0,0,0,0,1,0,Following Too Closely,Following Too Closely,Following Too Closely,Following Too Closely,Unsafe Speed
16315,2019-10-19T00:00:00.000,8:45,NaN,2.0,0.0,0,0,0,0,2,0,Following Too Closely,Driver Inexperience,Driver Inattention/Distraction,Following Too Closely,Unsafe Speed
16316,2019-08-20T00:00:00.000,22:00,NaN,1.0,0.0,0,0,0,0,1,0,Following Too Closely,Following Too Closely,Following Too Closely,Following Too Closely,Unsafe Speed
16317,2017-02-12T00:00:00.000,3:30,NaN,2.0,0.0,0,0,0,0,2,0,Unsafe Speed,Unsafe Speed,Unsafe Speed,Unsafe Speed,Unsafe Speed

In [65]:
col_list = ["NUMBER OF PERSONS KILLED","NUMBER OF PEDESTRIANS KILLED","NUMBER OF CYCLIST KILLED","NUMBER OF MOTORIST KILLED"]
data["Total killed"]=data[col_list].sum(axis=1)
col_list2 = ["NUMBER OF PERSONS INJURED","NUMBER OF PEDESTRIANS INJURED","NUMBER OF CYCLIST INJURED","NUMBER OF MOTORIST INJURED"]
data["Total injured"]=data[col_list2].sum(axis=1)
data

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,Total killed,Total injured
0,2019-08-11T00:00:00.000,22:23,NaN,0.0,1.0,0,0,0,0,0,1,Unsafe Speed,Unspecified,NaN,NaN,NaN,2.0,0.0
1,2019-08-09T00:00:00.000,6:00,STATEN ISLAND,2.0,0.0,0,0,0,0,2,0,Unsafe Speed,Unspecified,NaN,NaN,NaN,0.0,4.0
2,2019-08-17T00:00:00.000,2:45,NaN,2.0,0.0,0,0,0,0,2,0,Unsafe Speed,Unspecified,NaN,NaN,NaN,0.0,4.0
3,2019-08-30T00:00:00.000,17:15,NaN,1.0,0.0,0,0,0,0,1,0,Unsafe Speed,Driver Inattention/Distraction,Unspecified,Unspecified,NaN,0.0,2.0
4,2019-08-03T00:00:00.000,21:00,NaN,3.0,0.0,0,0,0,0,3,0,Unsafe Speed,Unspecified,Unspecified,NaN,NaN,0.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16313,2016-07-23T00:00:00.000,12:23,BRONX,0.0,0.0,0,0,0,0,0,0,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN,0.0,0.0
16314,2019-08-20T00:00:00.000,22:00,NaN,1.0,0.0,0,0,0,0,1,0,Following Too Closely,Following Too Closely,Following Too Closely,Following Too Closely,Unsafe Speed,0.0,2.0
16315,2019-10-19T00:00:00.000,8:45,NaN,2.0,0.0,0,0,0,0,2,0,Following Too Closely,Driver Inexperience,Driver Inattention/Distraction,Following Too Closely,Unsafe Speed,0.0,4.0
16316,2019-08-20T00:00:00.000,22:00,NaN,1.0,0.0,0,0,0,0,1,0,Following Too Closely,Following Too Closely,Following Too Closely,Following Too Closely,Unsafe Speed,0.0,2.0
16317,2017-02-12T00:00:00.000,3:30,NaN,2.0,0.0,0,0,0,0,2,0,Unsafe Speed,Unsafe Speed,Unsafe Speed,Unsafe Speed,Unsafe Speed,0.0,4.0

In [66]:
data2 = data[data['BOROUGH'].notna()]
data2

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,NUMBER OF PERSONS INJURED,NUMBER OF PERSONS KILLED,NUMBER OF PEDESTRIANS INJURED,NUMBER OF PEDESTRIANS KILLED,NUMBER OF CYCLIST INJURED,NUMBER OF CYCLIST KILLED,NUMBER OF MOTORIST INJURED,NUMBER OF MOTORIST KILLED,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,Total killed,Total injured
1,2019-08-09T00:00:00.000,6:00,STATEN ISLAND,2.0,0.0,0,0,0,0,2,0,Unsafe Speed,Unspecified,NaN,NaN,NaN,0.0,4.0
5,2019-08-26T00:00:00.000,1:00,BROOKLYN,0.0,0.0,0,0,0,0,0,0,Unsafe Speed,Unspecified,Unspecified,NaN,NaN,0.0,0.0
8,2019-08-11T00:00:00.000,12:27,BROOKLYN,1.0,1.0,0,0,0,1,1,0,Unsafe Speed,Unspecified,Unspecified,NaN,NaN,2.0,2.0
11,2019-08-19T00:00:00.000,16:30,BRONX,0.0,0.0,0,0,0,0,0,0,Unsafe Speed,Traffic Control Disregarded,NaN,NaN,NaN,0.0,0.0
12,2019-08-16T00:00:00.000,20:45,BROOKLYN,1.0,0.0,0,0,0,0,1,0,Unsafe Speed,Unspecified,Unspecified,Unspecified,Unspecified,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16301,2018-04-06T00:00:00.000,6:00,BROOKLYN,10.0,0.0,0,0,0,0,10,0,Following Too Closely,Following Too Closely,Following Too Closely,Unsafe Speed,NaN,0.0,20.0
16302,2018-03-22T00:00:00.000,9:00,BRONX,0.0,0.0,0,0,0,0,0,0,Other Vehicular,Other Vehicular,Other Vehicular,Unsafe Speed,NaN,0.0,0.0
16305,2018-02-06T00:00:00.000,0:20,QUEENS,0.0,0.0,0,0,0,0,0,0,Other Vehicular,Other Vehicular,Other Vehicular,Unsafe Speed,NaN,0.0,0.0
16310,2016-07-23T00:00:00.000,12:23,BRONX,0.0,0.0,0,0,0,0,0,0,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN,0.0,0.0
16313,2016-07-23T00:00:00.000,12:23,BRONX,0.0,0.0,0,0,0,0,0,0,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN,0.0,0.0

In [67]:
columns_list = ["NUMBER OF PERSONS INJURED","NUMBER OF PERSONS KILLED","NUMBER OF PEDESTRIANS INJURED","NUMBER OF PEDESTRIANS KILLED","NUMBER OF CYCLIST INJURED","NUMBER OF CYCLIST KILLED","NUMBER OF MOTORIST INJURED","NUMBER OF MOTORIST KILLED"]
data_for_plot = data2.drop(columns_list,axis=1)
data_for_plot

,ACCIDENT DATE,ACCIDENT TIME,BOROUGH,CONTRIBUTING FACTOR VEHICLE 1,CONTRIBUTING FACTOR VEHICLE 2,CONTRIBUTING FACTOR VEHICLE 3,CONTRIBUTING FACTOR VEHICLE 4,CONTRIBUTING FACTOR VEHICLE 5,Total killed,Total injured
1,2019-08-09T00:00:00.000,6:00,STATEN ISLAND,Unsafe Speed,Unspecified,NaN,NaN,NaN,0.0,4.0
5,2019-08-26T00:00:00.000,1:00,BROOKLYN,Unsafe Speed,Unspecified,Unspecified,NaN,NaN,0.0,0.0
8,2019-08-11T00:00:00.000,12:27,BROOKLYN,Unsafe Speed,Unspecified,Unspecified,NaN,NaN,2.0,2.0
11,2019-08-19T00:00:00.000,16:30,BRONX,Unsafe Speed,Traffic Control Disregarded,NaN,NaN,NaN,0.0,0.0
12,2019-08-16T00:00:00.000,20:45,BROOKLYN,Unsafe Speed,Unspecified,Unspecified,Unspecified,Unspecified,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...
16301,2018-04-06T00:00:00.000,6:00,BROOKLYN,Following Too Closely,Following Too Closely,Following Too Closely,Unsafe Speed,NaN,0.0,20.0
16302,2018-03-22T00:00:00.000,9:00,BRONX,Other Vehicular,Other Vehicular,Other Vehicular,Unsafe Speed,NaN,0.0,0.0
16305,2018-02-06T00:00:00.000,0:20,QUEENS,Other Vehicular,Other Vehicular,Other Vehicular,Unsafe Speed,NaN,0.0,0.0
16310,2016-07-23T00:00:00.000,12:23,BRONX,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN,0.0,0.0
16313,2016-07-23T00:00:00.000,12:23,BRONX,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Reaction to Uninvolved Vehicle,Unsafe Speed,NaN,0.0,0.0

In [ ]:
data_for_plot["Total killed"].plot(kind='hist')